"""Add verification_status to company_sources

Revision ID: 129ffb353b6b
Revises: 002_domain_aliases
Create Date: 2026-02-07 20:41:56.531932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129ffb353b6b'
down_revision: Union[str, None] = '002_domain_aliases'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_domain_aliases', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index(batch_op.f('ix_company_domain_aliases_alias_domain'))
        batch_op.create_index(batch_op.f('ix_company_domain_aliases_alias_domain'), ['alias_domain'], unique=True)
        batch_op.create_index(batch_op.f('ix_company_domain_aliases_id'), ['id'], unique=False)

    with op.batch_alter_table('company_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=False, server_default='verified'))
        batch_op.add_column(sa.Column('submitted_by', sa.String(length=255), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('source_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('last_scraped_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_company_sources_id'), ['id'], unique=False)

    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('HIGH', 'MEDIUM_HIGH', 'MEDIUM_LOW', 'LOW', 'TRANSFORMATIONAL', 'NO_SIGNAL', name='aireadinesscategory'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('HIGH', 'MEDIUM_HIGH', 'MEDIUM_LOW', 'LOW', 'TRANSFORMATIONAL', 'NO_SIGNAL', name='aireadinesscategory'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('company_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_sources_id'))
        batch_op.alter_column('last_scraped_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('source_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('submitted_by')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('company_domain_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_domain_aliases_id'))
        batch_op.drop_index(batch_op.f('ix_company_domain_aliases_alias_domain'))
        batch_op.create_index(batch_op.f('ix_company_domain_aliases_alias_domain'), ['alias_domain'], unique=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
