"""Add discovery_trace to Company

Revision ID: 604b561c99c9
Revises: b259375a2daf
Create Date: 2026-02-05 15:35:59.599823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604b561c99c9'
down_revision: Union[str, None] = 'b259375a2daf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('discovery_trace', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'discovery_trace')
    # ### end Alembic commands ###
