"""Add Score model

Revision ID: b259375a2daf
Revises: 001_initial
Create Date: 2026-02-03 23:40:01.268410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b259375a2daf'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.Enum('HIGH', 'MEDIUM_HIGH', 'MEDIUM_LOW', 'LOW', name='aireadinesscategory'), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_id'), 'scores', ['id'], unique=False)
    op.add_column('companies', sa.Column('domain', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('careers_url', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_column('companies', 'careers_url')
    op.drop_column('companies', 'domain')
    op.drop_index(op.f('ix_scores_id'), table_name='scores')
    op.drop_table('scores')
    # ### end Alembic commands ###
